- src/CMakeLists.txt
- src/ODE_solver.F90
- src/ODE_solvers/mozart.F90
- src/ODE_solvers/rosenbrock.F90
- src/kinetics.F90
- src/preprocessor_output/factor_solve_utilities.F90
- src/preprocessor_output/kinetics_utilities.F90
- src/preprocessor_output/rate_constants_utility.F90
- test/performance/CMakeLists.txt
- test/performance/driver.F90
- test/preprocessor_output/factor_solve_utilities.F90
- test/preprocessor_output/kinetics_utilities.F90
- test/preprocessor_output/rate_constants_utility.F90
closes #13 
- Introduces a test to the suite that can be expanded for use in the performance evaluation.
- We will have to set initial and evolving conditions once we get these from the scientists
- Adds multi-grid preprocessor output to the micm source code.
- Adapts `ODE_solver_t` and `kinetics_t` classes to work accept multi-grid-point data.
- For now, the solvers and kinetics classes only perform calculations for the first grid point, but the functions are now set up to accept multi-grid-point data
- I just bypassed the `core_t` class completely (excluding it from the build). This was easier than hacking in the multi-grid-point capability. The new test driver does the work that would have been handled by the `core_t` instance.
> add driver for performance tests

- include/micm/util/sparse_matrix.hpp
- test/unit/util/CMakeLists.txt
- test/unit/util/test_sparse_matrix.cpp
Adds a `SparseMatrix` class. This will be used for the Jacobian and linear solver functions.
The data structure follows the CSR pattern with the underlying matrix data stored in a `std::vector<double>`. The matrix structure is block-diagonal where each block is square and of the same dimensions and sparse structure. For the chemical system, the blocks should correspond to individual grid cells.
The `VectorId()` function allows for lookups of the index in the underlying vector for matrix elements using their block, row, and column indices. This can be saved and used for fast access during solving. Normal array syntax `[block][row][column]` access to matrix data is also available for more convenient (but slower) access.
I wasn't sure what is the best way to handle attempts to access zero …
> Sparse matrix class

- include/micm/process/process_set.hpp
- include/micm/solver/chapman_ode_solver.hpp
- include/micm/solver/rosenbrock.hpp
- include/micm/util/sparse_matrix.hpp
- test/regression/RosenbrockChapman/CMakeLists.txt
- test/regression/RosenbrockChapman/regression_test_dforce_dy.cpp
- test/unit/process/test_process_set.cpp
- test/unit/util/test_sparse_matrix.cpp
Adds the `dforce_dy()` function to the Rosenbrock solver.
The tests include a unit test for the `ProcessSet::AddJacobianTerms()` function, which does the actual calculations, but the regression test against the hard-coded Chapman solver is incomplete because the ordering of the sparse matrix Jacobian data appears to be different in the hard-coded array (maybe due to pivoting?).
As we go through the preprocessor logic to generalize the linear solver functions we should be able to extract the logic to translate the hard-coded sparse matrix data and finish the `dforce_dy` regression test.
> Rosenbrock dforce_dy function

- CMakeLists.txt
- Dockerfile.nvhpc
- README.md
- cmake/dependencies.cmake
- cmake/test_util.cmake
- include/micm/process/process_set_cuda.hpp
- include/micm/process/process_set_openacc.hpp
- src/CMakeLists.txt
- src/process/CMakeLists.txt
- src/process/process_set.cpp
- src/process/process_set.cu
- test/unit/process/CMakeLists.txt
- test/unit/process/test_cuda_process_set.cpp
- test/unit/process/test_openacc_process_set.cpp
- Adds support for building openacc
- Wraps cuda and openacc code in their own namespaces so that function names can be the same if desired
1. Setup a localrc file
```
makelocalrc -d . -x -gcc /glade/u/apps/gust/23.04/spack/opt/spack/ncarcompilers/0.8.0/gcc/12.2.0/bin/gcc -gpp /glade/u/apps/gust/23.04/spack/opt/spack/ncarcompilers/0.8.0/gcc/12.2.0/bin/g++ -g77 /glade/u/apps/gust/23.04/spack/opt/spack/ncarcompilers/0.8.0/gcc/12.2.0/bin/gfortran
```
2. Start a session
```
qinteractive -A<AccountNumber> --ngpus=1
```
3. Tell nvidia to use this file. 
```
export NVLOCALRC=/glade/u/home/kshores/localrc
```
4. Load the modules
```
module load nvhpc/23.1 cmake/3.25
```
5. Build micm with open acc
```
cd micm/build
cmake -DENABLE_OPENACC=ON -DENABLE_REGESSION_TESTS=OFF -D GPU_TYPE="cc80"  ..
``` …
> Enable openacc

- Dockerfile.nvhpc
- cmake/test_util.cmake
- src/CMakeLists.txt
- src/process/CMakeLists.txt
- test/unit/process/CMakeLists.txt
Creates a separate target for cuda and openacc. This means that tests that need to use code for either must explicitly link to that library
> creating a separate cuda and openacc target

- include/micm/solver/linear_solver.hpp
- include/micm/solver/lu_decomposition.hpp
- include/micm/solver/rosenbrock.hpp
- include/micm/util/sparse_matrix.hpp
- test/unit/solver/CMakeLists.txt
- test/unit/solver/test_lu_decomposition.cpp
- test/unit/util/test_sparse_matrix.cpp
Adds an LU decomposer class to close #65 
The `factor()` function in the hard-coded solver was performing an LU decomposition. The `LuDecomposition::Decompose()` function is its replacement for the general Rosenbrock solver.
Also includes the draft of a `LinearSolver` class that will hold the remaining formerly preprocessed functions as they are generalized. Once this is finished, `LinearSolver` will be usable by the `Rosenbrock` solver and any other ODE solver that may be added in the future.
Also adds support for `const SparseMatrix`
> LU decomposition

- include/micm/process/process_set.hpp
- include/micm/solver/lu_decomposition.hpp
- include/micm/util/matrix.hpp
- include/micm/util/sparse_matrix.hpp
- include/micm/util/sparse_matrix_standard_ordering.hpp
- include/micm/util/sparse_matrix_vector_ordering.hpp
- include/micm/util/standard_sparse_matrix.hpp
- include/micm/util/vector_matrix.hpp
- test/unit/process/test_process_set.cpp
- test/unit/solver/test_lu_decomposition.cpp
- test/unit/util/CMakeLists.txt
- test/unit/util/test_sparse_matrix_policy.hpp
- test/unit/util/test_sparse_matrix_standard_ordering.cpp
- test/unit/util/test_sparse_matrix_vector_ordering.cpp
- test/unit/util/test_vector_matrix.cpp
Adds a sparse matrix that is structured to encourage vectorization. Updates the `ProcessSet::AddJacobianTerms()` and `LuDecomposition::Decompose()` functions to support the new sparse matrix.
Replaces the term "block" in the `VectorMatrix` class with "group" to avoid confusion with blocks in the block-diagonal sparse matrix. "Group" is now used in dense and sparse matrices to refer to the rows that are grouped together to encourage vectorization. The number of rows in a group is the template parameter in both `VectorMatrix` and `SparseMatrixVectorOrdering`
Closes #94
> Vectorizable Sparse Matrix

- include/micm/solver/chapman_ode_solver.hpp
In preparation for moving the `ChapmanODESolver` to the tests, this PR removes its dependence on `RosenbrockSolver`
> Remove RosenbrockSolver inheritence from ChapmanODESolver

- include/micm/solver/rosenbrock.hpp
- include/micm/util/sparse_matrix.hpp
- test/unit/solver/test_rosenbrock.cpp
Creates a general-use function for calculating `[ alpha * I - jacobian ]`. Moves the call to the LU factorization out of the this function for easier testing.
closes #107
> Finish AlphaMinusJacobian function

- .github/workflows/test.yml
- Dockerfile.intel
- include/micm/configure/solver_config.hpp
- test/regression/RosenbrockChapman/chapman_ode_solver.hpp
I think there is only one remaining warning. It's with nvhpc, and I'm pretty sure it's incorrectly applied:
```
"/micm/test/regression/RosenbrockChapman/regression_test_solve.cpp", line 57: warning: ignoring return value type with "nodiscard" attribute [nodiscard_return_type]
fixed_results[i] = fixed_solver.Solve(0.0, 500.0, fixed_state);
^
Remark: individual warnings can be suppressed with "--diag_suppress <warning-name>"
```
I opted to leave our code unchanged, instead of trying to get rid of the warning.
closes #138
> Address compiler warnings

- include/micm/solver/linear_solver.hpp
- include/micm/solver/rosenbrock.hpp
- include/micm/system/system.hpp
- test/regression/RosenbrockChapman/regression_test_dforce_dy.cpp
- test/regression/RosenbrockChapman/regression_test_p_force.cpp
- test/regression/RosenbrockChapman/regression_test_solve.cpp
- test/unit/solver/test_linear_solver.cpp
- test/unit/solver/test_rosenbrock.cpp
- test/unit/system/test_system.cpp
Adds a function that performs Diagonal Markowitz reordering of the solver state variables to minimize fill-in during LU decomposition. Includes the reordering by default in the `RosenbrockSolver` but allows disabling the reordering with a solver parameter.
The algorithm is based on Stacy's write up (https://github.com/NCAR/micm-preprocessor/blob/2de3a3c6234d8629520debfc463f572ad5666d4c/documentation/pivot_algorithm.txt#L1-L65) and his original CAM-Chem preprocessor code (https://github.com/ESCOMP/CHEM_PREPROCESSOR/blob/944f506033d88a5dd1ee4556a932d2c90023cbfc/src/cam_chempp/sp_utils.f#L130-L194).
closes #116
> State reordering

- include/micm/configure/solver_config.hpp
- include/micm/process/tunneling_rate_constant.hpp
- test/unit/configure/process/CMakeLists.txt
- test/unit/configure/process/test_tunneling_config.cpp
- test/unit/process/CMakeLists.txt
- test/unit/process/test_ternary_chemical_activation_rate_constant.cpp
- test/unit/process/test_tunneling_rate_constant.cpp
- test/unit/unit_configs/process/tunneling/missing_products/reactions.json
- test/unit/unit_configs/process/tunneling/missing_products/species.json
- test/unit/unit_configs/process/tunneling/missing_products/tolerance.json
- test/unit/unit_configs/process/tunneling/missing_reactants/reactions.json
- test/unit/unit_configs/process/tunneling/missing_reactants/species.json
- test/unit/unit_configs/process/tunneling/missing_reactants/tolerance.json
- test/unit/unit_configs/process/tunneling/valid/reactions.json
- test/unit/unit_configs/process/tunneling/valid/species.json
- test/unit/unit_configs/process/tunneling/valid/tolerance.json
Adds a `TunnelingRateConstant` class to handle reactions described [here](https://open-atmos.github.io/camp/html/camp_rxn_wennberg_tunneling.html)
Leaving off documentation pending #154 
closes #148
> Tunneling reaction rate constant

- include/micm/configure/solver_config.hpp
- include/micm/process/branched_rate_constant.hpp
- include/micm/util/constants.hpp
- test/unit/configure/process/CMakeLists.txt
- test/unit/configure/process/test_branched_config.cpp
- test/unit/process/CMakeLists.txt
- test/unit/process/test_branched_rate_constant.cpp
- test/unit/unit_configs/process/branched/missing_alkoxy_products/reactions.json
- test/unit/unit_configs/process/branched/missing_alkoxy_products/species.json
- test/unit/unit_configs/process/branched/missing_alkoxy_products/tolerance.json
- test/unit/unit_configs/process/branched/missing_nitrate_products/reactions.json
- test/unit/unit_configs/process/branched/missing_nitrate_products/species.json
- test/unit/unit_configs/process/branched/missing_nitrate_products/tolerance.json
- test/unit/unit_configs/process/branched/missing_reactants/reactions.json
- test/unit/unit_configs/process/branched/missing_reactants/species.json
- test/unit/unit_configs/process/branched/missing_reactants/tolerance.json
- test/unit/unit_configs/process/branched/valid/reactions.json
- test/unit/unit_configs/process/branched/valid/species.json
- test/unit/unit_configs/process/branched/valid/tolerance.json
Adds a `BranchedRateConstant` class to handle a special branched reaction for NO + RO2 reactions, where the branching ratio depends on environmental conditions.
Does not include documentation pending #154
closes #147
> Branched NO + RO2 reaction

- include/micm/solver/rosenbrock.hpp
- test/integration/analytical.cpp
- test/regression/RosenbrockChapman/chapman_ode_solver.hpp
- test/regression/RosenbrockChapman/regression_test_solve.cpp
Fixed a few logic issues in the solver
- calculating the jacobian exactly once for each phase of the solver
- calculating an initial forcing which I had removed previously, not realizing that when rejecting an `H`, the initial forcing is used
- setting some of the same parameters as KPP
- setting the right size for `Yerror`
- added a `NaN` check
> Parameter fixes

- test/unit/solver/test_linear_solver_policy.hpp
Fixes a missing namespace in the linear solver tests
> fix missing namespace in linear solver test

- .github/workflows/gh_pages.yml
- CMakeLists.txt
- README.md
- docs/source/conf.py
- docs/switcher.json
- test/integration/analytical.cpp
Closes #236, which really was already done. The main version of the docs **should** be released when we do the release
> 236 set up micm documentation builds and gh pages

- CMakeLists.txt
- include/micm/process/process.hpp
- include/micm/solver/rosenbrock.hpp
- include/micm/solver/rosenbrock.inl
- test/unit/process/CMakeLists.txt
- test/unit/process/test_process.cpp
Adds a rate constant calculation function for `VectorMatrix`. I didn't add a JITed version of this function because there is no indirect addressing and so it probably wouldn't benefit from JIT compiling.
closes #193
> Develop 193 jit rate constants

- README.md
- include/micm/solver/rosenbrock.hpp
- include/micm/util/sparse_matrix.hpp
- test/tutorial/test_README_example.cpp
- test/tutorial/test_rate_constants_no_user_defined_by_hand.cpp
- test/tutorial/test_rate_constants_no_user_defined_with_config.cpp
Adds a `StandardSparseMatrix` alias to the `micm` namespace to simplify tutorial examples.
The docs are available [here](https://ncar.github.io/micm/branch/develop-windows-tutorial/user_guide/index.html)
> Develop windows tutorial

- .github/workflows/test.yml
This adds tests that build on macos 12 and 13 with different versions
This would close #157, though I don't actually know if we need these or not. Feel free to reject this if you think these are superfluous
> 157 steal the tests from the json library to test xcode builds

- CODE_OF_CONDUCT.md
- README.md
- docs/source/contributing/index.rst
- docs/source/user_guide/rate_constant_tutorial.rst
Closes #276
Docs can be viewed here: https://ncar.github.io/micm/branch/276-add-code-of-conduct-and-contributor-guide/contributing/index.html
> adding code of conduct and contributors guide

- .github/workflows/gh_pages.yml
The switcher on the [docs](https://ncar.github.io/micm/) doesn't work because the switcher.json file isn't copied correctly. Hopefully this fixes it.
You can see that the switcher [doesn't exist at the root of the branch where it needs to be](https://github.com/NCAR/micm/tree/gh-pages).
> hopefully copying the switcher

- README.md
These don't need to be on the home page
> removing documentation dependencies from readme

- include/micm/process/process.hpp
- include/micm/process/process_set.hpp
- include/micm/solver/rosenbrock.hpp
- include/micm/solver/rosenbrock.inl
- include/micm/system/phase.hpp
- include/micm/system/species.hpp
- include/micm/system/system.hpp
- test/integration/CMakeLists.txt
- test/integration/jit_terminator.cpp
- test/integration/terminator.cpp
- test/integration/terminator.hpp
- test/unit/process/test_process.cpp
- test/unit/process/test_process_set_policy.hpp
- test/unit/system/test_phase.cpp
- test/unit/system/test_species.cpp
- test/unit/system/test_system.cpp
closes #245 
Includes the analytical solution from CAM-Chem in the test for the Terminator configuration.
Also, I updated slightly the logic around min/max/initial solver time steps to avoid changing solver parameters during the solve and to allow users to be able to specify these (which I did in the terminator test to get closer results to the analytical solution).
And, I added the ability to include species whose concentrations are not solved for, but are parameterized on environmental conditions. At first I did this because I mistakenly thought the third-body species "M" was included in the Terminator configuration. I left this option in the PR because it will be useful for other mechanisms that include "M" and for setting constant values for species like O2 and N2
> Develop 245 terminator

- include/micm/process/process.hpp
- include/micm/system/species.hpp
- test/unit/process/test_process.cpp
Closes #165
- Adds a test to ensure surface reaction rates aren't created with more than one reactant
#Issues
- First order loss and emissions reaction emissions also should only accept one reactant. However, both of these are represented as a `UserDefinedRateConstant` which can be first order loss, emission, or photolysis, and photolysis reactions can have more than one reactant. There is no clean way to ensure that first order loss reactions and emission reactions have exactly one reactant.
- This actually isn't a problem. Our json parsing code has a check for these conditions implicitly. It's only in the construction of a process by hand that someone could make a rate constant process for loss or emission with more than one reactant. That's a bug, but it's a user error. Unless we …
> Validation checks

- include/micm/system/phase.hpp
- test/integration/terminator.cpp
- test/integration/terminator.hpp
Uses an alias for some template arguments and relaxes tolerances in terminator test to hopefully fix failing tests.
> Bug fix build

- .github/workflows/clang_format.yml
- include/micm/solver/jit_linear_solver.hpp
- include/micm/solver/jit_linear_solver.inl
- include/micm/solver/jit_lu_decomposition.hpp
- include/micm/solver/jit_lu_decomposition.inl
- include/micm/solver/linear_solver.hpp
- include/micm/solver/linear_solver.inl
- include/micm/solver/lu_decomposition.hpp
- include/micm/solver/lu_decomposition.inl
- include/micm/solver/rosenbrock.hpp
- include/micm/solver/rosenbrock.inl
- test/integration/terminator.cpp
- test/unit/solver/test_jit_lu_decomposition.cpp
- test/unit/solver/test_lu_decomposition.cpp
- test/unit/solver/test_lu_decomposition_policy.hpp
closes #82 
Adds an option to the `RosenbrockSolver` to perform a check for singularity. The `JitLuDecomposition::Factor` function calls the base class function when checking for singularity, until we decide it's worthwhile to have a JITed version of the LU factorization that does this check.
> Develop 82 singular matrix

- include/micm/configure/solver_config.hpp
- include/micm/process/arrhenius_rate_constant.hpp
- include/micm/process/branched_rate_constant.hpp
- include/micm/process/surface_rate_constant.hpp
- include/micm/process/ternary_chemical_activation_rate_constant.hpp
- include/micm/process/troe_rate_constant.hpp
- include/micm/process/tunneling_rate_constant.hpp
- include/micm/process/user_defined_rate_constant.hpp
- test/unit/configure/process/test_emission_config.cpp
- test/unit/configure/process/test_first_order_loss_config.cpp
- test/unit/configure/process/test_photolysis_config.cpp
- test/unit/configure/process/test_user_defined_config.cpp
- test/unit/process/test_user_defined_rate_constant.cpp
- test/unit/unit_configs/process/emission/valid/reactions.json
- test/unit/unit_configs/process/first_order_loss/valid/reactions.json
- test/unit/unit_configs/process/photolysis/valid/reactions.json
- test/unit/unit_configs/process/user_defined/valid/reactions.json
closes #330 
Adds the ability to parse scaling factors for user-defined rate constants (e.g., emissions, photolysis, first-order loss)
> Parse scaling factors

- include/micm/process/ternary_chemical_activation_rate_constant.hpp
- include/micm/process/troe_rate_constant.hpp
In Troe and Ternary reactions, changed rate constant expressions to allow for N = 0.
closes #349
> Changed rate constant expression to allow for N = 0.

- include/micm/configure/solver_config.hpp
- include/micm/solver/state.inl
- test/unit/configure/process/test_arrhenius_config.cpp
- test/unit/configure/process/test_branched_config.cpp
- test/unit/configure/process/test_ternary_chemical_activation_config.cpp
- test/unit/configure/process/test_troe_config.cpp
- test/unit/configure/process/test_tunneling_config.cpp
- test/unit/configure/test_solver_config.cpp
closes #337 
Introduces the conversion of parameters from the OpenAtmos configuration format to account for the use of SI units in MICM. A separate issue will be created on the https://github.com/NCAR/micm-kpp/ repo to account for this change.
> Develop 337 non si units

- include/micm/solver/cuda_linear_solver.cuh
- include/micm/solver/cuda_linear_solver.hpp
- include/micm/util/cuda_param.hpp
- src/process/process_set.cu
- src/solver/linear_solver.cu
This PR introduces a new constructor/destructor to the `CudaLinearSolver` class that handles the data movement between host and device. It also cleans up some interfaces and adds more comments for future information.
By using the following env on Derecho,
```
Currently Loaded Modules:
1) ncarenv/23.09 (S)   2) nvhpc/23.7   3) gcc-toolchain/12.2.0   4) hdf5/1.12.2   5) netcdf/4.9.2   6) ncarcompilers/1.0.0   7) cmake/3.26.3   8) cuda/12.2.1
```
All the 39 unit tests passed.
Fixed #389
> Create constructor/destructor for `CudaLinearSolver` class to handle data movement between host and device

- include/micm/solver/cuda_linear_solver.hpp
Previously unused constructor now acts as the base constructor and the working constructor calls the base constructor with additional arguments.
> Adding missing constructor implementaion.

- include/micm/util/cuda_vector_matrix.cuh
- include/micm/util/cuda_vector_matrix.hpp
- include/micm/util/vector_matrix.hpp
- src/util/cuda_vector_matrix.cu
- test/unit/util/test_cuda_vector_matrix.cpp
Adds assignment and move operators and constructors so a CudaVectorMatrix can be assigned to another  which generates new device data for the newly assigned vector or moves the other vector into the new vector while in that case taking ownership of the other matrix's device memory.
> 416 add assignment overridescopy constructors to cudavectormatrix so new matrix has separate device memory

- include/micm/process/cuda_process_set.cuh
- include/micm/process/cuda_process_set.hpp
- include/micm/process/process_set.hpp
- include/micm/util/cuda_param.hpp
- include/micm/util/cuda_vector_matrix.hpp
- src/process/process_set.cu
- src/solver/rosenbrock.cu
- src/util/cuda_vector_matrix.cu
- test/unit/process/test_cuda_process_set.cpp
- test/unit/solver/CMakeLists.txt
- test/unit/util/cuda_matrix_utils.cu
This PR updates the input type for the CUDA implementation of `AddforcingTerms` function with the `CudaVectorMatrix` class.
I have to comment out the `test_cuda_rosenbrock` test for now because it requests me to update all the other CUDA kernels to pass. The other 40 tests all passed on Derecho's A100 GPU by using `nvhpc/23.7`
> Update the CUDA implementation of AddforcingTerms with the CudaVectorMatrix class

- .github/workflows/mac.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
- include/micm/solver/state.hpp
- include/micm/solver/state.inl
- test/integration/analytical_policy.hpp
- test/unit/solver/test_state.cpp
To support https://github.com/NCAR/musica/issues/79, we will need to allow the interfaces with fortran and python to somehow set custom rate parameters. We only accept mappings as of now. This adds a new methods that takes a vector of vectors and assumes that the order of rate constants is already correct.
> Allow custom rate parameters to be directly set

- include/micm/process/cuda_process_set.cuh
- include/micm/process/cuda_process_set.hpp
- include/micm/solver/cuda_linear_solver.cuh
- include/micm/solver/cuda_linear_solver.hpp
- include/micm/util/cuda_dense_matrix.hpp
- include/micm/util/cuda_matrix.cuh
- include/micm/util/cuda_param.hpp
- include/micm/util/cuda_sparse_matrix.hpp
- src/process/process_set.cu
- src/solver/linear_solver.cu
- src/solver/rosenbrock.cu
- src/util/CMakeLists.txt
- src/util/cuda_matrix.cu
- test/unit/process/test_cuda_process_set.cpp
- test/unit/util/CMakeLists.txt
- test/unit/util/cuda_matrix_utils.cu
- test/unit/util/cuda_matrix_utils.cuh
- test/unit/util/test_cuda_dense_matrix.cpp
- test/unit/util/test_cuda_sparse_matrix.cpp
This PR renames the previous `CudaVectorMatrix` class to `CudaDenseMatrix` class for clarity. Now we only have `CudaDenseMatrix` and `CudaSparseMatrix`, and they are only for the vector matrix on GPU.
Maybe we should highlight somewhere that the GPU code only works with the vector matrix?
All the 40 tests passed on Derecho's A100 GPU by using `nvhpc/23.7`.
Fixed #442
> Rename CUDA matrix class to be Dense or Sparse

- include/micm/process/cuda_process_set.cuh
- include/micm/process/cuda_process_set.hpp
- src/process/process_set.cu
- test/unit/process/test_cuda_process_set.cpp
This PR updates the input type for the CUDA implementation of `SubtractJacobianTerms` function with the `CudaDenseMatrix` and `CudaSparseMatrix` class.
All the 40 tests all passed on Derecho's A100 GPU by using `nvhpc/23.7`.
> Update the CUDA implementation of SubtractJacobianTerms with the CUDA matrix class

- include/micm/configure/solver_config.hpp
- include/micm/process/surface_rate_constant.hpp
- include/micm/system/species.hpp
- test/unit/configure/test_solver_config.cpp
- test/unit/system/test_species.cpp
- test/unit/unit_configs/chapman/species.json
Adds support for non-double species properties. Closes #407
> add support for non-double properties

- include/micm/solver/cuda_lu_decomposition.hpp
- include/micm/solver/jit_lu_decomposition.inl
- include/micm/solver/linear_solver.inl
- include/micm/solver/lu_decomposition.hpp
- include/micm/solver/lu_decomposition.inl
- include/micm/solver/state.inl
- test/unit/solver/test_cuda_lu_decomposition.cpp
- test/unit/solver/test_linear_solver_policy.hpp
- test/unit/solver/test_lu_decomposition.cpp
- test/unit/solver/test_lu_decomposition_policy.hpp
Modifies existing `LuDecomposition` functions to consistently use template arguments for the data type and sparse matrix policy, removing the `SparseMatrixOrderingPolicy`.
closes #453
> Update template arguments for LuDecomposition

- include/micm/solver/rosenbrock_solver_parameters.hpp
- include/micm/system/species.hpp
- test/unit/system/test_species.cpp
Adds descriptive messages to exceptions thrown when looking up nonexistent species properties.
Also adds a missing header include.
> Add exceptions for species property lookups

- include/micm/solver/cuda_rosenbrock.cuh
- include/micm/solver/cuda_rosenbrock.hpp
- include/micm/solver/rosenbrock_solver_parameters.hpp
- include/micm/util/cuda_dense_matrix.hpp
- include/micm/util/cuda_matrix.cuh
- include/micm/util/cuda_param.hpp
- include/micm/util/cuda_sparse_matrix.hpp
- src/solver/rosenbrock.cu
- src/util/cuda_matrix.cu
- test/unit/process/test_troe_rate_constant.cpp
- test/unit/solver/CMakeLists.txt
- test/unit/solver/test_cuda_rosenbrock.cpp
This PR updates the input type for the CUDA implementation of `AlphaMinusJacobian` and `NormalizedError` functions with the `CudaDenseMatrix` and `CudaSparseMatrix` class.
It also addresses some issues related to the copy/move constructor/assignment/destructor in the `CudaDenseMatrix` and `CudaSparseMatrix` class.
All the 41 tests all passed on Derecho's A100 GPU by using `nvhpc/23.7`.
> Update the CUDA implementation of AlphaMinusJacobian and NormalizedError with the CUDA matrix class

- include/micm/solver/rosenbrock.inl
- include/micm/util/cuda_dense_matrix.hpp
- include/micm/util/matrix.hpp
- include/micm/util/vector_matrix.hpp
- src/util/cuda_matrix.cu
- test/unit/util/test_cuda_dense_matrix.cpp
This PR introduces a new `Copy` function in both the CPU and GPU matrix class.
In the CPU matrix class, it simply calls the `assign` function.
In the GPU matrix class, it only copies the device data.
All the 42 tests all passed on Derecho's A100 GPU by using `nvhpc/23.7`.
fix #471
> Update the assign function inside both CPU and GPU class

- .clang-tidy
Added the `cert-*` checks to .clang-tidy.  Removed two relating to the random number generators as they were used primarily in the tests and those instance need to be reproducible.  Also removed cert-err58-cpp as this would require changing `static const std::string`'s to `const char*`.
Closes #520
> 520 clang tidy cert additions

- .github/workflows/clang-tidy.yml
- .github/workflows/clang_format_non_inline.yml
- .github/workflows/docker_and_coverage.yml
- .github/workflows/gh_pages.yml
- .github/workflows/mac.yml
- .github/workflows/ubuntu.yml
- .github/workflows/windows.yml
Change the permissions to run on workflow dispatch or a pull request, rather than every push
> actions run on workflow dispatch or pr

- cmake/test_util.cmake
- test/unit/process/CMakeLists.txt
- test/unit/solver/CMakeLists.txt
- test/unit/util/CMakeLists.txt
This PR adds `compute-sanitizer` to check the GPU memory leak for all the CUDA tests.
Note that the `compute-sanitizer` looks for CUDA APIs in a code and will issue an error when applied to a CPU test. This error could not be suppressed unfortunately (https://docs.nvidia.com/compute-sanitizer/ComputeSanitizer/index.html#error-suppression). Therefore, we add new internal options to apply the `compute-sanitizer` check to the CUDA tests only.
All the 50 tests (including GPU memory check) are passed on Derecho's A100 GPU, using the `nvhpc/23.7`.
fix #415
> Add GPU memory check for CUDA code

- cmake/test_util.cmake
This PR adds a non-zero exiting code for `compute-santizer` when it finishes a run and detects a memory leak. Therefore, a test with memory leak will fail as expected.
fix #552
> Add exiting error code for compute-sanitizer

- include/micm/solver/backward_euler.inl
- test/integration/analytical_jit_rosenbrock.cpp
- test/integration/analytical_policy.hpp
- test/integration/analytical_rosenbrock.cpp
- test/integration/analytical_surface_rxn_policy.hpp
Closes #499 
Backward euler passes all tests, but the robertson tests (the solver fails to converge and seems to get stuck, will be investigated by #498). I don't know how to test backward euler against HIRES, Oregonator, E5, but hopefully that can be fixed with #575
> testing backward euler with most of the analytical tests

- include/micm/solver/rosenbrock.inl
Removes the use of `AsVector()` for setting the L and U matrices to zero in the Rosenbrock solve function, which is incompatible with the CUDA implementation
> Use Fill to reset the L and U matrices in Rosenbrock solve

- cmake/test_util.cmake
- include/micm/cuda/process/cuda_process_set.cuh
- include/micm/cuda/process/cuda_process_set.hpp
- include/micm/cuda/solver/cuda_linear_solver.hpp
- include/micm/cuda/solver/cuda_lu_decomposition.hpp
- include/micm/cuda/solver/cuda_rosenbrock.hpp
- include/micm/cuda/util/cuda_param.hpp
- include/micm/process/process_set.hpp
- include/micm/solver/linear_solver.hpp
- include/micm/solver/lu_decomposition.hpp
- include/micm/solver/rosenbrock.hpp
- include/micm/solver/solver.hpp
- src/process/process_set.cu
- src/solver/linear_solver.cu
- src/solver/lu_decomposition.cu
- src/solver/rosenbrock.cu
This PR:
- use the correct option `--leak-check full` for `compute-sanitizer` to check the memory leak on the GPU.
- fix a GPU memory leak due to the missing of `cudaFree` for a bool pointer on the GPU.
- fix multiple GPU memory leaks by using `std::swap` rather than `std::move` in the move constructor and assignment in a CUDA class.
All the GPU unit tests are now passed for GPU memory check on Derecho's A100 GPU. The integration test is not checked for GPU memory leak because it takes too long.
fix #598
> Fix GPU memory leak for the CUDA unit tests

- examples/configs/TS1/species.json
- examples/configs/carbon_bond_5/species.json
- examples/configs/chapman/species.json
- include/micm/configure/solver_config.hpp
- include/micm/system/species.hpp
- test/integration/test_chapman_integration.cpp
- test/unit/configure/test_solver_config.cpp
- test/unit/unit_configs/small_mechanism/species.json
Fix #613. The full writeup is in the issue, but ensuring that the species object in the list of products and reactants contains information on whether something is a third body by copying the value from the species array during a read of a configuration file allows the process set to properly detect if a species is a third body or not and fixes our usage of third body species
> Correct usage of third body species

- include/micm/solver/solver.hpp
Correct the constructor of the solver. Apparently this was preventing part of musica from building. I don't understand it
> correcting solver builder constructor

- test/unit/cuda/process/test_cuda_process_set.cpp
- test/unit/cuda/solver/test_cuda_linear_solver.cpp
- test/unit/cuda/solver/test_cuda_lu_decomposition.cpp
This PR fixes the broken GPU unit tests with nvhpc/24.7 on Derecho by using a relative tolerance rather than an exact equal match. This seems to be a compiler issue as nvhpc/23.7 on Derecho can pass the equal check with the same setup.
fix #617
> Relax the criteria to pass the GPU test with nvhpc/24.7 on Derecho

- include/micm/cuda/util/cuda_dense_matrix.hpp
- include/micm/cuda/util/cuda_matrix.cuh
- include/micm/cuda/util/cuda_sparse_matrix.hpp
- src/util/cuda_matrix.cu
- test/unit/cuda/util/test_cuda_dense_matrix.cpp
This PR:
- removes the data transfer between host and device in the CUDA dense matrix constructor
- templates the CUDA functions used in the CUDA matrix class to remove the requirement of `double` data type
fix #628 
fix #629
> Remove data transfer in cuda matrix constructor and template some CUDA functions

- include/micm/solver/backward_euler.inl
- include/micm/solver/rosenbrock.inl
Replaces a local copy of the system state variables in the Rosenbrock and Backward Euler solver functions with a reference to the function argument.
> Remove local copy of state in solver functions

- cmake/test_util.cmake
- include/micm/cuda/util/cuda_dense_matrix.hpp
- include/micm/cuda/util/cuda_param.hpp
- include/micm/cuda/util/cuda_util.cuh
- src/process/process_set.cu
- src/solver/linear_solver.cu
- src/solver/lu_decomposition.cu
- src/solver/rosenbrock.cu
- src/util/cuda_matrix.cu
- src/util/cuda_util.cu
- test/integration/cuda/CMakeLists.txt
- test/unit/cuda/util/CMakeLists.txt
- test/unit/cuda/util/cuda_gtest_main.cpp
- test/unit/cuda/util/test_cuda_dense_matrix.cpp
This PR:
- adds a singleton class to generate the CUDA streams
- makes all the CUDA kernel launches asynchronously
- modifies the default `main()` function for GTest to clean up the CUDA streams before the program exits
All the unit tests passed on Derecho's A100 GPU with `nvhpc/24.7`.
> Add CUDA stream for asynchronous kernel launch

- include/micm/solver/rosenbrock.inl
This PR:
- removes the generation of local copy of Jacobian matrix
- reconstructs the Jacobian matrix when a substepping is needed for the LU decomposition
fix #644
> Remove the local copy of Jacobian matrix when doing LU decomposition

- include/micm/cuda/solver/cuda_linear_solver.hpp
- include/micm/cuda/solver/cuda_lu_decomposition.hpp
- include/micm/cuda/solver/cuda_rosenbrock.hpp
- include/micm/solver/rosenbrock.inl
- test/unit/cuda/solver/test_cuda_rosenbrock.cpp
> Use CUDA Rosenbrock parameters

- include/micm/cuda/util/cuda_param.hpp
- include/micm/solver/solver.hpp
This PR:
- changes `BLOCK_SIZE` to 512 based on my profiling results.
- adds back the `GetNumberOfReactions` function, which is needed for the performance repo.
fix #632
> Misc updates

- include/micm/solver/backward_euler.inl
- include/micm/solver/backward_euler_solver_parameters.hpp
- include/micm/solver/rosenbrock.inl
To make it easy to test backward euler in the performance repository, I've added `h_start` to the backward euler parameters. This means we can use the same testing code for rosenbrock or backward euler
> Set hstart to timestep

- .github/workflows/mac.yml
- include/micm/solver/rosenbrock.hpp
- include/micm/solver/rosenbrock.inl
Inside the convergence loop of the Rosenbrock solver there may be repeated calls to `AbstractRosenbrockSolver::LinearFactor()`. Because this function overwrites the negative jacobian stored in `state.jacobian_`, the alpha values from successive calls accumulate along the diagonal.
This apparently didn't have enough of an impact to affect the results of the analytical tests, but should be corrected.
I wasn't sure of the best way to test this fix, because the impact was small and we don't currently have unit tests for the `AbstractRosenbrockSolver::Solve()` function because exact outputs are difficult to calculate. If anyone has suggestions for tests, I can add them.
> Fixes a bug in the logic used to calculate alpha - jacobian

- include/micm/process/process_set.hpp
- include/micm/solver/linear_solver_in_place.inl
- include/micm/solver/lu_decomposition_doolittle_in_place.inl
- include/micm/solver/lu_decomposition_mozart_in_place.inl
As suggested by Matt, I revised the `i_cell` loop to increase the iterator explicitly rather than use the `[]` syntax.
This improves the CPU performance for gcc, intel and nvhpc compilers on Derecho.
> Improve the CPU performance by increasing the iterator directly

- include/micm/solver/solver_builder.inl
- test/integration/test_analytical_backward_euler.cpp
There was a bug in the creation of the linear solver when using in-line LU decomposition. This fixes it and adds a test of the in-line BE solver for the HIRES test, which was failing before the bug was fixed.
> Fix bug in inline BE solver

- .github/workflows/windows.yml
- CMakeLists.txt
- include/micm/solver/rosenbrock.hpp
- include/micm/solver/rosenbrock.inl
- test/integration/test_analytical_rosenbrock.cpp
This PR fixes a potential issue of using Rosenbrock solver with inline LU decomposition algorithm, when a substepping happens.
Basically we need to:
- re-compute the Jacobian matrix after each sub step because the Jacobian matrix is now modified by the LU decomposition algorithm in place
- only keep the `last_alpha` code for the non-inline LU decomposition algorithm.
fix #704
> Fix substepping issue for Rosenbrock solver with inline LU decomposition

- .github/workflows/close_stale_issues.yml
This workflow is modified from the CIME repo workflow (https://github.com/ESMCI/cime/blob/master/.github/workflows/stale.yml) and is expected to close any issues or PRs that have no activity within the past 30 days.
I try to add comments for most settings and we can discuss what is the best value for the MICM repo.
fix #728
> Add a workflow to close stale issue/PR

- include/micm/solver/state.inl
- test/unit/solver/test_state.cpp
Adds a test of the state's default constructor, fixes a memory error
> adding state default constructor test

- include/micm/util/property_keys.hpp
When using std::string, we were running into a [static initialization problem](https://stackoverflow.com/a/1005709/5217293) (also see the [linked article](https://isocpp.org/wiki/faq/ctors#static-init-order) in the answer for more detail). This apparently isn't a problem within the library, but attempting to use those values in the musica performance repo caused this issue to pop up here and in [mechanism configuration](https://github.com/NCAR/MechanismConfiguration/pull/85).
> dealing with static initializaiton issue

- include/micm/solver/solver.hpp
- test/unit/solver/test_solver_builder.cpp
Adds a function to the Solver class that can be used to get the maximum number of grid cells that can fit in one group of vectorized State matrices.
> Add maximum grid cells function

- include/micm/util/sparse_matrix.hpp
- test/unit/util/test_sparse_matrix_policy.hpp
- test/unit/util/test_sparse_matrix_standard_ordering_column.cpp
- test/unit/util/test_sparse_matrix_standard_ordering_row.cpp
- test/unit/util/test_sparse_matrix_vector_ordering_column.cpp
- test/unit/util/test_sparse_matrix_vector_ordering_row.cpp
fix #778 
Thanks @mattldawson for the suggestions.
> Add a new print function to print non-zero elements of a sparse matrix

- include/micm/cuda/util/cuda_dense_matrix.hpp
- include/micm/cuda/util/cuda_sparse_matrix.hpp
- include/micm/solver/linear_solver.inl
- include/micm/solver/linear_solver_in_place.inl
- include/micm/solver/lu_decomposition.hpp
- include/micm/solver/lu_decomposition_doolittle.hpp
- include/micm/solver/lu_decomposition_doolittle.inl
- include/micm/solver/lu_decomposition_doolittle_in_place.hpp
- include/micm/solver/lu_decomposition_doolittle_in_place.inl
- include/micm/solver/lu_decomposition_mozart.hpp
- include/micm/solver/lu_decomposition_mozart.inl
- include/micm/solver/lu_decomposition_mozart_in_place.hpp
- include/micm/solver/lu_decomposition_mozart_in_place.inl
- include/micm/solver/solver_builder.inl
- include/micm/solver/state.inl
- include/micm/util/jacobian.hpp
- include/micm/util/sparse_matrix.hpp
- test/unit/solver/test_linear_solver_in_place_policy.hpp
- test/unit/solver/test_linear_solver_policy.hpp
- test/unit/solver/test_lu_decomposition_in_place_policy.hpp
- test/unit/solver/test_lu_decomposition_policy.hpp
This pull request
- avoids the allocation of two separate large sparse matrices when generating the Jacobian matrix and ALU matrix.
- avoids the undesired allocation of a Jacobian matrix on the GPU with `number_of_grid_cells` dimension when calling the `BuildJacobian` function.
- removes the `number of grid cells` argument from the `GetLuMatrix` function since we can always derive it from the matrix argument now and use the `indexing_only` flag to control the actual allocation.
It passes all the unit tests on Derecho's A100 GPUs and it runs with 1.6 million grid cells on Casper's A100 80GB GPU. 
Thanks @K20shores and @mattldawson for your help.
fix #776 
fix #782
> Address out of memory error on GPU with large number of grid cells

- include/micm/process/phase_transfer_process.hpp
- include/micm/process/phase_transfer_process_builder.hpp
- test/unit/process/test_process.cpp
In `PhaseTransferProcess` there will only ever be one gas-phase species. This PR corrects the data type for it
```C++
// previous
std::vector<Species> gas_species_;
// this PR
Species gas_species_;
```
> Correct the data type for storing gas species in PhaseTransferProcess
