NCAR/micm

Dockerfile
etc/rate_constant_demo/src/rate_constant_factory.F90
etc/rate_constant_demo/src/rate_constants/bar.F90
etc/rate_constant_demo/src/rate_constants/foo.F90
src/ODE_solver.F90
src/ODE_solver_factory.F90
src/ODE_solvers/mozart.F90
src/ODE_solvers/rosenbrock.F90
src/core.F90

================================================
Tag name:
Originator(s):
Date:
Issue(s) resolved:
One-line Summary:
Purpose of changes:
Files added:
Files deleted:
Files modified:
Regression test status:

add preprocessor functions

---

src/core.F90

================================================
Tag name:
Originator(s):
Date:
Issue(s) resolved:
One-line Summary:
Purpose of changes:
Files added:
Files deleted:
Files modified:
Regression test status:

update for domain refactor

---

src/ODE_solvers/mozart.F90
src/ODE_solvers/rosenbrock.F90
src/core.F90

================================================
Tag name:
Originator(s):
Date:
Issue(s) resolved:
One-line Summary:
Purpose of changes:
Files added:
Files deleted:
Files modified:
Regression test status:

Develop 46 camp

---

include/micm/micm.h
src/micm.cpp
test/integration/CMakeLists.txt
test/integration/c_host.c

================================================
Tag name:
Originator(s):
Date:
Issue(s) resolved:
One-line Summary:
Purpose of changes:
Files added:
Files deleted:
Files modified:
Regression test status:

draft C host test

---

Dockerfile

updates the `musica-core` library and does a "utility only" build

update musica-core lib; switch to util-only build

---

.clang-format
include/micm/process/arrhenius_rate_constant.hpp
include/micm/process/external_rate_constant.hpp
include/micm/process/intraphase_process.hpp
include/micm/process/intraphase_process_builder.hpp
src/CMakeLists.txt
src/process/CMakeLists.txt
src/process/intraphase_process.cpp
src/process/intraphase_process_builder.cpp
src/system/CMakeLists.txt
src/system/condition.cpp
src/system/species.cpp
src/system/system.cpp
src/version.cpp.in
test/unit/process/CMakeLists.txt
test/unit/process/test_intraphase_process.cpp
test/unit/process/test_intraphase_process_builder.cpp

26 create intraphaseprocess and intraphaseprocessbuilder classes

---

Dockerfile
include/micm/process/arrhenius_rate_constant.hpp
include/micm/solver/chapman_ode_solver.hpp
include/micm/solver/solver.hpp
test/regression/CMakeLists.txt
test/regression/configs/solver.json
test/regression/dforce_dy.F90
test/regression/kinetic_solve.F90
test/regression/old_micm/src/ODE_solvers/rosenbrock.F90
test/regression/old_micm/src/kinetics.F90
test/regression/p_force.F90
test/regression/rate_constants.F90
test/regression/regression_test_arrhenius.cpp
test/regression/regression_test_dforce_dy.cpp
test/regression/regression_test_kinetic_solve.cpp
test/regression/regression_test_p_force.cpp
test/regression/regression_test_solve.cpp
test/regression/solve.F90
test/unit/process/test_arrhenius_rate_constant.cpp
test/unit/solver/test_chapman_ode_solver.cpp

Closes #48. Adds more unit tests as well and changed the return type of a solver

48 add remaining rosenbrock ros3 only functions to chapmanodesolver

---

test/integration/chapman.cpp

Fixes an uncaught merge conflict for PRs #92 and #93

add template parameter to Rosenbrock Solver test

---

CMakeLists.txt

Updating version number for the release

updating version number

---

README.md

hello, I added the changes you wanted.
can you please give me your idea of it?
also, I added the build and installation according to the [tuv-x](https://github.com/NCAR/tuv-x) readme. md
hope you will like it
if there you want me to fix something I will be more than happy to do it.
thanks for the option to learn and work with you
closes #95

Add build instructions to the readme

---

include/micm/solver/chapman_ode_solver.hpp
include/micm/solver/rosenbrock.hpp
include/micm/solver/solver.hpp
include/micm/util/matrix.hpp
include/micm/util/vector_matrix.hpp
test/integration/chapman.cpp
test/regression/RosenbrockChapman/CMakeLists.txt
test/regression/RosenbrockChapman/regression_test_dforce_dy.cpp
test/regression/RosenbrockChapman/regression_test_p_force.cpp
test/regression/RosenbrockChapman/regression_test_solve.cpp
test/unit/solver/test_rosenbrock.cpp
test/unit/util/test_matrix.cpp
test/unit/util/test_matrix_policy.hpp
test/unit/util/test_vector_matrix.cpp

Finishes the `RosenbrockSolver::Solve()` function and tests against hard-coded `ChapmanODESolver::Solve()`
Closes #112
Closes #51

General Rosenbrock Solver

---

.github/workflows/test.yml
Dockerfile.intel
README.md
include/micm/configure/solver_config.hpp
test/regression/RosenbrockChapman/chapman_ode_solver.hpp
test/regression/RosenbrockChapman/regression_test_p_force.cpp

Adds a relative tolerance to Rosenbrock forcing regression tests to avoid failures with large random numbers

Add relative tolerance to regression tests

---

etc/configs/kpp/arr.eqn
etc/configs/kpp/arr.spc
etc/scripts/kpp_to_micm.py
etc/scripts/test_kpp_to_micm.py

- Start on test_kpp_to_micm pytest unit tests
- Added method kpp_to_micm.parse_kpp_arrhenius
- Added --kpp_name argument to filter kpp config files found in --kpp_dir
- Reworked some KPP equation parsing

Kpp to micm

---

test/unit/process/test_cuda_process_set.cpp

new branch created out of main for debugging. Deleted a line in test_cuda_process_set.hpp. Now compiled without error and AddJacobianTerms still passed.

Debug main

---

include/micm/process/jit_process_set.hpp

Adds a Jacobian term calculation function to `JitProcessSet`. The current tests cover this function already as it overrides the existing base `ProcessSet` function.
Closes #194

Develop jit jacobian function

---

test/integration/analytical.cpp

fixes a bug that popped up in the merging of PR #221

fix solver test

---

include/micm/solver/rosenbrock.hpp
include/micm/solver/rosenbrock.inl
test/unit/solver/test_rosenbrock.cpp

closes #219 
This is a compile-time decision that will record timing or not for the jacobian, forcing, linear solve, and linear factor

adding timing functions

---

.github/workflows/clang_format.yml

I think this closes #203, but I'm sure. We'll have to see what happens when this runs

only create the formatting branch if changes are detected

---

.devcontainer/devcontainer.json
docs/source/user_guide/jit.rst
test/tutorial/test_jit_tutorial.cpp

Adds build instructions to the JIT tutorial

Develop jit tutorial edits

---

docker/Dockerfile
include/micm/process/process_set.hpp
include/micm/solver/rosenbrock.inl
include/micm/solver/rosenbrock_solver_parameters.hpp
test/integration/chapman.cpp
test/regression/RosenbrockChapman/jit_util.hpp
test/regression/RosenbrockChapman/util.hpp
test/unit/process/test_process_set_policy.hpp

Check for unused species in solver constructor

---

include/micm/util/constants.hpp

Adjust the Boltzmann constant to match what's used in the ChemistryCafe

Update Boltzmann constant

---

CMakeLists.txt
README.md
docs/source/_static/switcher.json
docs/source/conf.py
include/micm/version.hpp
test/integration/cmake/find_package/CMakeLists.txt

v3.3.1 Release

---

include/micm/solver/rosenbrock.inl

Resets the lower and upper matrices to zero at the beginning of the solve function

reseting matrices

---

CITATION.cff
CMakeLists.txt
docs/source/_static/switcher.json
docs/source/conf.py
include/micm/version.hpp

Update the version for new release

Release v3.4.0

---

.github/workflows/clang_format.yml
.github/workflows/clang_format_non_inline.yml

Adds version output and verbose file lists to determine which specific files are being found and forwarded to `clang-format`.
Added a job that will always succeed to show the formats for debugging purposes on each push.

Initial attempt to format cuda code.

---

.github/workflows/clang_format.yml
.github/workflows/clang_format_non_inline.yml

Addresses missing `-` before `name` in previous PR and adds new file extensions to format job that runs on push.

Fixing bugs in previous PR.

---

include/micm/configure/solver_config.hpp
include/micm/jit/jit_compiler.hpp
include/micm/process/process.hpp
include/micm/process/process_set.hpp
include/micm/process/rate_constant.hpp
include/micm/solver/rosenbrock.inl
include/micm/solver/state.inl
include/micm/system/species.hpp
include/micm/util/matrix_error.hpp

Adds missing `inline` for header functions

make error code functions inline

---

.clang-format
include/micm/util/cuda_dense_matrix.hpp
include/micm/util/cuda_matrix.cuh
include/micm/util/cuda_sparse_matrix.hpp
include/micm/util/matrix.hpp
include/micm/util/sparse_matrix.hpp
src/solver/rosenbrock.cu
src/util/cuda_matrix.cu
test/unit/openmp/run_solver.hpp
test/unit/openmp/test_openmp.cpp
test/unit/openmp/test_openmp_jit_solver.cpp

Fix regex in clang-format

---

test/unit/util/test_cuda_dense_matrix.cpp
test/unit/util/test_cuda_sparse_matrix.cpp

This PR fixes the issue found in #458 based on my knowledge but I am happy to check more things if they are missing.
If I misunderstand the issue somehow, please let me know as well.

Check if the device pointer is initialized to nullptr in the move constructor

---

.github/workflows/mac.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
examples/profile_example.cpp

Closes #490 
Removed the outdated `ConfigParseStatus` 
Added it to the git actions

Fix the profiler driver 

---

include/micm/solver/backward_euler.inl
test/unit/solver/test_backward_euler.cpp

Fix the broken main

---

include/micm/version.hpp
src/version.hpp.in
test/unit/version/test_version.cpp

CamelCase for getting version 

---

.github/workflows/new_issue.yml

Attempts to add an action that assigns new issues to our MUSICA project board

Add new issues to project board

---

.github/workflows/docker_and_coverage.yml
.github/workflows/ubuntu.yml

Disables Intel tests until an open issue with Intel is addressed and #541 is fixed.

Disable Intel tests

---

CITATION.cff
docs/source/_static/switcher.json

Update the version to v3.5.0

---

include/micm/solver/solver.hpp

fix https://github.com/NCAR/MUSICA-Performance-Comparison/issues/52

Provide a way to access the processes_ data member

---

test/unit/cuda/CMakeLists.txt
test/unit/cuda/util/test_cuda_sparse_matrix.cpp

Add back two missing CUDA unit tests and fix a broken path after the reordering of header files

Add missing CUDA tests and fix broken path

---

.github/workflows/mac.yml
.github/workflows/ubuntu.yml
.github/workflows/windows.yml
docker/Dockerfile.memcheck
include/micm/jit/solver/jit_linear_solver.hpp
include/micm/jit/solver/jit_linear_solver.inl
include/micm/solver/rosenbrock.hpp
include/micm/solver/rosenbrock.inl

Adds the `const` qualifier to solver functions that should not be modifying object data. Also removes collection of profiling data during actions to reduce runtime.

Add const to solver functions

---

include/micm/solver/rosenbrock.inl

Moved the yError outside of the While loop
closes #622

Move Yerror construction outside of the inner solve loop for rosenbrock

---

include/micm/cuda/util/cuda_dense_matrix.hpp
include/micm/cuda/util/cuda_matrix.cuh
include/micm/solver/solver.hpp
include/micm/solver/solver_result.hpp
include/micm/util/matrix.hpp
include/micm/util/vector_matrix.hpp
src/util/cuda_matrix.cu
test/tutorial/test_multiple_grid_cells.cpp
test/tutorial/test_rate_constants_no_user_defined_by_hand.cpp
test/tutorial/test_rate_constants_no_user_defined_with_config.cpp
test/tutorial/test_rate_constants_user_defined_by_hand.cpp
test/tutorial/test_rate_constants_user_defined_with_config.cpp
test/tutorial/test_solver_configuration.cpp
test/tutorial/test_vectorized_matrix_solver.cpp
test/unit/cuda/util/test_cuda_dense_matrix.cpp
test/unit/util/test_matrix.cpp
test/unit/util/test_matrix_policy.hpp
test/unit/util/test_vector_matrix.cpp

Adds a filter to the Solver class's Solve function to remove negative results. Also corrects logic in tutorial code for accumulating solver timing output.

Filter zeros in solver results

---

include/micm/util/matrix.hpp
include/micm/util/sparse_matrix.hpp
include/micm/util/vector_matrix.hpp
test/unit/util/test_matrix.cpp
test/unit/util/test_matrix_policy.hpp
test/unit/util/test_sparse_matrix_policy.hpp
test/unit/util/test_sparse_matrix_standard_ordering_column.cpp
test/unit/util/test_sparse_matrix_standard_ordering_row.cpp
test/unit/util/test_sparse_matrix_vector_ordering_column.cpp
test/unit/util/test_sparse_matrix_vector_ordering_row.cpp
test/unit/util/test_vector_matrix.cpp

Adds the ability to print out matrix data to an output stream.

Matrix print

---

include/micm/solver/solver_builder.inl
include/micm/solver/state.hpp
test/unit/solver/test_state.cpp

corrected the move assignment constructor, added test for all copy/move/assignment operations on the state class

correcting more state constructors, adding tests

---

include/micm/solver/solver.hpp

Adds the State and Solver policy types to the Solver class

Add types to solver class

---

CITATION.cff
CMakeLists.txt
README.md
docs/source/_static/switcher.json
include/micm/version.hpp

Update the version
